# Generated by Django 5.2.4 on 2025-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=40)),
                ('cv_url', models.URLField()),
                ('contact_button_name', models.CharField(max_length=40)),
                ('mobile_url', models.URLField()),
            ],
        ),
    ]
