# Generated by Django 5.2.4 on 2025-07-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
